// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations if available, fallback to DATABASE_URL
    // DIRECT_URL only needed for local migrations, not production
    url: env("DIRECT_URL") || env("DATABASE_URL"),
  },
});

