// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DATABASE_URL (pooler with IPv4) for migrations
    // DIRECT_URL is IPv6-only and may not work on all networks
    url: process.env.DIRECT_URL || env("DATABASE_URL"),
  },
});

